// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0KKN445pE4rK9EJ1H3OD6ENbRdlr9gMc',
    appId: '1:563383791047:web:88b24304fb8e09319dbde2',
    messagingSenderId: '563383791047',
    projectId: 'sigilborne-ddm',
    authDomain: 'sigilborne-ddm.firebaseapp.com',
    storageBucket: 'sigilborne-ddm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUu7BGSiDRXcuexskvwDMBjqzuL1thjJ8',
    appId: '1:563383791047:android:1f94b573503f44359dbde2',
    messagingSenderId: '563383791047',
    projectId: 'sigilborne-ddm',
    storageBucket: 'sigilborne-ddm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBERgmWWnfWpEY_k7d4Y8lLU-4fCcQeO9Q',
    appId: '1:563383791047:ios:50f06a94d4b5d9159dbde2',
    messagingSenderId: '563383791047',
    projectId: 'sigilborne-ddm',
    storageBucket: 'sigilborne-ddm.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBERgmWWnfWpEY_k7d4Y8lLU-4fCcQeO9Q',
    appId: '1:563383791047:ios:50f06a94d4b5d9159dbde2',
    messagingSenderId: '563383791047',
    projectId: 'sigilborne-ddm',
    storageBucket: 'sigilborne-ddm.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0KKN445pE4rK9EJ1H3OD6ENbRdlr9gMc',
    appId: '1:563383791047:web:8d7001bbeae221949dbde2',
    messagingSenderId: '563383791047',
    projectId: 'sigilborne-ddm',
    authDomain: 'sigilborne-ddm.firebaseapp.com',
    storageBucket: 'sigilborne-ddm.firebasestorage.app',
  );
}
